---
name: Ruby build

on:
  push:
    branches:
      - main
    paths:
      - 'ruby-engine/**'
      - 'yggdrasilffi/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches:
      - main
    paths:
      - 'ruby-engine/**'
      - 'yggdrasilffi/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  workflow_dispatch:

jobs:
  build-ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile default
          rustup show

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Get client spec
        uses: actions/checkout@v6
        with:
          repository: Unleash/client-specification
          ref: v5.2.2
          path: client-specification

      - name: Run cargo tests
        run: cargo test --all-features

      - name: Build ffi binaries for Ruby
        working-directory: ruby-engine
        run: bash ./build.sh

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Ruby dependencies
        working-directory: ruby-engine
        run: |
          gem install bundler --no-document
          bundle install
          gem install rspec --no-document

      - name: Run Ruby tests
        working-directory: ruby-engine
        run: rspec
