name: Publish .NET
on:
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Extract Yggdrasil Core Version
        id: extract_ffi_version
        run: |
          sudo apt-get install -y xmlstarlet
          cd dotnet-engine/Yggdrasil.Engine
          CORE_VERSION=$(xmlstarlet sel -t -v "/Project/PropertyGroup/YggdrasilCoreVersion" -n Yggdrasil.Engine.csproj)
          echo "FFI Library Version: $CORE_VERSION"
          echo "CORE_VERSION=$CORE_VERSION" >> $GITHUB_ENV

      - name: Download binaries
        shell: bash
        working-directory: ./dotnet-engine
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download "yggdrasilffi-v$CORE_VERSION" --repo Unleash/yggdrasil-bindings -D binaries/

      - name: Build
        run: |
          cd dotnet-engine
          dotnet restore dotnet-engine.sln
          dotnet build dotnet-engine.sln -c Release --no-restore
          dotnet pack dotnet-engine.sln -c Release --no-build --no-restore

      - name: Check package size
        run: |
          cd dotnet-engine
          ls -lh Yggdrasil.Engine/bin/Release/*nupkg

      - name: Publish package
        run: |
          cd dotnet-engine
          dotnet nuget push Yggdrasil.Engine/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
      - name: Make a tag for the dotnet release
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/dotnet-engine-v$CORE_VERSION',
              sha: context.sha
            })